### PR TITLE
Added baseline statistics for Cox

### PR DESCRIPTION
**Pull request by piever**
This is part 4 of #5 . I've added three functions to get baseline hazard, cumulative hazard and survival functions of a fitted CoxModel and added some docs.

### CODE REVIEW

**Comment by piever** [comment]
I'm not sure what should `baseline_survival` (and similar) return: now it gives a pair of vectors (`times` and `values`), but maybe it should give a function that can be tested on any new value, like `ecdf`? Or maybe even both and we could create new type that has both `x` and `y` fields (with these vectors) but is also callable. What do you think?

**Comment by nalimilan** [comment]
I agree it makes sense to return a special distribution object. I think there have been discussions about how to represent empirical distributions in the same framework as the Distributions packages. @andreasnoack knows better.

**Comment by piever** [comment]
That'd be very helpful. I should probably leave as is here for now and maybe we can open an issue about this at `StatsBase` (where I think this kind of object should be defined)? I think the new type should have `x` and `y` field for the specific points, a `f` field with the function and potentially a few constructors to simplify building `f` in the common cases.

**Comment by nalimilan** [comment]
I guess the type would be defined in this package, but it could inherit from and implement an abstract type defined e.g. in Distributions.

**Pull request closed without merging**
